
#define FTDIPIO_IOC_MAGIC 0x41

#define FTDIPIO_IOC_RESET _IO(FTDIPIO_IOC_MAGIC, 0)

#define FTDIPIO_IOC_PURGE_BUFFERS _IO(FTDIPIO_IOC_MAGIC, 1)
#define FTDIPIO_IOC_SET_LATENCY_TIMER _IOW(FTDIPIO_IOC_MAGIC, 2, unsigned char)
#define FTDIPIO_IOC_GET_LATENCY_TIMER _IOR(FTDIPIO_IOC_MAGIC, 3, unsigned char)


