/* File auto-generated - do not modify */

/*
	FileName :		DRIVER_CONF.H

	Content :		settings of the driver properties

	Used in :		Driver

	Programmer :		Laurent GROSS

	Version :		Unified-6.0

	Support :		mail to : fec-support@ires.in2p3.fr

	Last modification :	03/05/2005

	Remarks :		This file should not be modified by users ;
				File auto-generated by Makefile from driver.conf descriptions.
*/


/*
This file is part of Fec Software project.

Fec Software is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Fec Software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Fec Software; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Copyright 2002 - 2005, Laurent GROSS - IReS/IN2P3
*/


/* Begin Block - avoid multiple inclusions of this file */
#ifndef DD_DRIVERCONF_H
#define DD_DRIVERCONF_H


#ifdef __cplusplus
extern "C" {
#endif


#define DD_MINOR	0

#define DD_DEVICE	"/dev/fecpmc00"

#define DD_MODULE	"fecpmc00"

#define DD_MAJOR	247

#define DD_FEC_NUMBER	0


#ifdef __cplusplus
}
#endif


/* End Block - avoid multiple inclusions of this file */
#endif

